title: 李会超
description: A iOS Developer

url: http://aochuih.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

excerpt_separator: "<!--more-->"

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: 首页
   url: /index.html
 - title: 关于
   url: /about

social:
   github: aochuih
   twitter: aochuih
   facebook: lihuichaoo
   email: lihuichaoo@gmail.com

google_analytics: "UA-81666116-1"
